# Generated by Django 4.1.7 on 2023-03-23 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0002_auto_20201124_0614"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="date_of_admission",
            new_name="date_of_Joining",
        ),
    ]
