# Generated by Django 4.1.7 on 2023-04-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(
                choices=[
                    ("Admission Fee", "Admission Fee"),
                    ("Exam Fee", "Exam Fee"),
                    ("Annual Function", "Annual Function"),
                    ("Festival Fee", "Festival Fee"),
                    ("Library Fee", "Library Fee"),
                    ("Electricity", "Electricity"),
                    ("School Development", "School Development"),
                    ("Id card, Diary, Belt & Tie", "Id card, Diary, Belt & Tie"),
                    ("Tution Fee", "Tution Fee"),
                ],
                max_length=200,
            ),
        ),
    ]
