# Generated by Django 4.1.7 on 2023-03-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_invoice_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(
                choices=[
                    ("a", "Admission Fee"),
                    ("b", "Tution Fee"),
                    ("c", "Library Fee"),
                    ("d", "Hostel Fee"),
                    ("e", "Sports Fee"),
                    ("f", "Management Fee"),
                    ("g", "Others"),
                ],
                max_length=200,
            ),
        ),
    ]
