# Generated by Django 4.1.7 on 2023-03-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_invoiceitem_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(
                choices=[
                    ("Admission Fee", "Admission Fee"),
                    ("Tution Fee", "Tution Fee"),
                ],
                max_length=200,
            ),
        ),
    ]
