# Generated by Django 4.1.7 on 2023-03-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_alter_invoiceitem_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="description",
            field=models.CharField(
                choices=[
                    ("Admission Fee", "Admission Fee"),
                    ("Tution Fee", "Tution Fee"),
                    ("Exam Fee", "Exam Fee"),
                    ("Annual Function", "Annual Function"),
                    ("Festival Fee", "Festival Fee"),
                    ("Library Fee", "Library Fee"),
                    ("School Development", "School Development"),
                    ("ID card, Diary, Belt & Tie", "ID card, Diary, Belt & Tie"),
                    ("Electricity", "Electricity"),
                    ("Others", "Others"),
                ],
                max_length=200,
            ),
        ),
    ]
