# Generated by Django 4.1.7 on 2023-03-15 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_auto_20201124_0614"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="account_no",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered bank account number isn't in a right format!",
                        regex="^[0-9]{10,20}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="birth_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="students/birth_certificate/"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="branch_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="cluster_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="country",
            field=models.CharField(default="India", max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="district",
            field=models.CharField(default="Barpeta", max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="educational_block",
            field=models.CharField(default="Bhabanipur Block", max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="fathers_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="student",
            name="mothers_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="name_of_the_bank",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="pin",
            field=models.CharField(
                default=None,
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered Pin number isn't in a right format!",
                        regex="^[0-9]{5,7}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="state",
            field=models.CharField(default="Assam", max_length=200),
        ),
    ]
