# Generated by Django 4.1.7 on 2023-03-15 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_student_account_no_student_birth_certificate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["firstname", "surname"]},
        ),
    ]
