# Generated by Django 4.1.7 on 2023-03-23 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_alter_student_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="Students_Category",
            field=models.CharField(
                choices=[
                    ("General", "General"),
                    ("SC", "SC"),
                    ("ST", "ST"),
                    ("OBC", "OBC"),
                    ("MOBC", "MOBC"),
                    ("Others", "Others"),
                ],
                default="General",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="aadhaar_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="please entere a correct Aadhar number !",
                        regex="^[0-9]{11,13}$",
                    )
                ],
            ),
        ),
    ]
